name: Build and Deploy Docker Image

on:
  push:
    branches:
      - master 
  pull_request:
    branches:
      - master 

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
 
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }} 
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker Image
      run: |
        docker build \
          --build-arg GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} \
          -t JulianHL/b2-gym-app:latest ./B2GYMBinder/

    - name: Push Docker Image
      run: |
        docker push JulianHL/b2-gym-app:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Deploy Application
      run: |
        docker pull JulianHL/b2-gym-app:latest
        docker stop b2-gym-app || true
        docker rm b2-gym-app || true
        docker run -d \
          --name b2-gym-app \
          -e GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }} \
          -p 8501:8501 \
          JulianHL/b2-gym-app:latest
